### ISSUE TITLE
page counts overwritten

### ISSUE THREAD

**Issue by andrewd72** [Perlkonig/grav-plugin-count-views#1]
I'm not 100% sure how it is supposed to work but at the moment /user/data/count-views.yaml is only recording the last viewed page, not a record of all the page views. Thanks.

**Comment by Perlkonig** [comment]
You should be seeing something like the following (from my YAML file):

``` yaml
/: 507
/blog/tripwire-by-lee-child: 3
/demos: 32
/blog/die-trying-by-lee-child: 3
/blog/panic-virus-by-seth-mnookin: 3
/blog/recipes-bread-week: 1
```

**Comment by andrewd72** [comment]
I only ever get one line so the count is max 1. 
e.g. /blog/mypage/: 1
then if I go to a different page it gets replaced rather than appending the new line.

**Comment by andrewd72** [comment]
It IS working on my remote server! That is on php7, 
localhost is on php 5.6.25, I think that is the only difference between them.

**Comment by Perlkonig** [comment]
Hrm. I don't know enough about the differences to know if that's a possible cause.

**Comment by Perlkonig** [comment]
Did you ever figure this out? I'd  need a copy of your user folder to replicate.
