### ISSUE TITLE
Error after update to version 3.0.0

### ISSUE THREAD

**Issue by awrog** [Perlkonig/grav-plugin-count-views#10]
Had version 2.0.0 of this fine plugin working perfectly (simple knowledgebase site).
After updating I get the following error: "The sort filter only works with arrays or "Traversable", got "NULL"."

Log
```[2018-07-17 11:20:03] grav.CRITICAL: The sort filter only works with arrays or "Traversable", got "NULL". - Trace: #0 /home/lrpdoc/domains/lrp-doc.pkn.nl/public_html/kb/cache/twig/35/35083547502f059f9242f9f60b9854d805dfd88f4d449c296f9fb2a0139b0029.php(126): twig_sort_filter(NULL) #1 /home/lrpdoc/domains/lrp-doc.pkn.nl/public_html/kb/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_f5376a2d840f02515332314b320c5b5509e6c91ac30f4e4acf1d6d254bacec75->doDisplay(Array, Array) #2 /home/lrpdoc/domains/lrp-doc.pkn.nl/public_html/kb/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array) #3 /home/lrpdoc/domains/lrp-doc.pkn.nl/public_html/kb/cache/twig/01/0160eaedde4909107bb9228f4abe97005729bed630b17ef603cbcc8a7c59e76d.php(272): Twig_Template->display(Array) #4 /home/lrpdoc/domains/lrp-doc.pkn.nl/public_html/kb/vendor/twig/twig/lib/Twig/Template.php(215): __TwigTemplate_0aabf0e3e5d85c011302ff5d21183d0086934b018c7f40b1b8331eeb0c12d267->block_sidebar(Array, Array) #5 /home/lrpdoc/domains/lrp-doc.pkn.nl/public_html/kb/cache/twig/01/0160eaedde4909107bb9228f4abe97005729bed630b17ef603cbcc8a7c59e76d.php(84): Twig_Template->displayBlock('sidebar', Array, Array) #6 /home/lrpdoc/domains/lrp-doc.pkn.nl/public_html/kb/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_0aabf0e3e5d85c011302ff5d21183d0086934b018c7f40b1b8331eeb0c12d267->doDisplay(Array, Array) #7 /home/lrpdoc/domains/lrp-doc.pkn.nl/public_html/kb/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array) #8 /home/lrpdoc/domains/lrp-doc.pkn.nl/public_html/kb/cache/twig/9f/9fd95655bb97726e5221ce151ded7d86a983b738977cbb9b9a8b0982277aa373.php(24): Twig_Template->display(Array, Array) #9 /home/lrpdoc/domains/lrp-doc.pkn.nl/public_html/kb/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_cc75bb45309107610e369a672a6bd97554ee75fcbd2338c284eb3446738e314a->doDisplay(Array, Array) #10 /home/lrpdoc/domains/lrp-doc.pkn.nl/public_html/kb/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array) #11 /home/lrpdoc/domains/lrp-doc.pkn.nl/public_html/kb/vendor/twig/twig/lib/Twig/Template.php(411): Twig_Template->display(Array) #12 /home/lrpdoc/domains/lrp-doc.pkn.nl/public_html/kb/vendor/twig/twig/lib/Twig/Environment.php(363): Twig_Template->render(Array) #13 /home/lrpdoc/domains/lrp-doc.pkn.nl/public_html/kb/system/src/Grav/Common/Twig/Twig.php(351): Twig_Environment->render('front.html.twig', Array) #14 /home/lrpdoc/domains/lrp-doc.pkn.nl/public_html/kb/system/src/Grav/Common/Service/OutputServiceProvider.php(27): Grav\Common\Twig\Twig->processSite('html') #15 /home/lrpdoc/domains/lrp-doc.pkn.nl/public_html/kb/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Common\Service\OutputServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav)) #16 /home/lrpdoc/domains/lrp-doc.pkn.nl/public_html/kb/system/src/Grav/Common/Processors/RenderProcessor.php(19): Pimple\Container->offsetGet('output') #17 /home/lrpdoc/domains/lrp-doc.pkn.nl/public_html/kb/system/src/Grav/Common/Grav.php(132): Grav\Common\Processors\RenderProcessor->process() #18 /home/lrpdoc/domains/lrp-doc.pkn.nl/public_html/kb/system/src/Grav/Common/Grav.php(374): Grav\Common\Grav->Grav\Common\{closure}() #19 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('render', 'Render', Object(Closure)) #20 /home/lrpdoc/domains/lrp-doc.pkn.nl/public_html/kb/system/src/Grav/Common/Grav.php(350): call_user_func_array(Object(Closure), Array) #21 /home/lrpdoc/domains/lrp-doc.pkn.nl/public_html/kb/system/src/Grav/Common/Grav.php(133): Grav\Common\Grav->__call('measureTime', Array) #22 /home/lrpdoc/domains/lrp-doc.pkn.nl/public_html/kb/system/src/Grav/Common/Grav.php(133): Grav\Common\Grav->measureTime('render', 'Render', Object(Closure)) #23 /home/lrpdoc/domains/lrp-doc.pkn.nl/public_html/kb/index.php(52): Grav\Common\Grav->process() #24 {main} [] []```

**Comment by Perlkonig** [comment]
Uhm, that's no good. Can you send me the Twig you're using? Sorry! Obviously I need to expand my test cases!

**Comment by Perlkonig** [comment]
Are you using the deprecated-now-removed interface? The only interface now is `viewcounts`:

`{% for route,views in viewcounts|sort|reverse|slice(0,10) %}`

**Comment by awrog** [comment]
It's the standard knowlegdebase skeleton (to my knowledge).
Excuse my ignorance for uploading the complete user directory. (no sensitive data there)

**Comment by Perlkonig** [comment]
Well this is embarrassing. My theme was using the deprecated interface. Fixing it now. Look for a new release. Sorry for the trouble.
