### ISSUE TITLE
working with error

### ISSUE THREAD

**Issue by abooks23** [Perlkonig/grav-plugin-count-views#13]
Hi
example 1post, 2post
i open 1post count change to 1
i open 2post count change to 1, but 1post count change to null,
if i after that open 1post - count change to 1, but 2post count change to null,

add many posts, maximum one post have counter=1. other = null
insert  {{ viewcounts[page.route] }}

**Comment by Perlkonig** [comment]
Are you testing on Windows? There's a known issue with file locking. I just 
haven't had time to find a workaround.

**Comment by abooks23** [comment]
yes windows lcalhost...
