### ISSUE TITLE
How to display views on my blog pages

### ISSUE THREAD

**Issue by blackyzero** [Perlkonig/grav-plugin-count-views#3]
Hi everyone,

i installed count-views plugin, enabled it, and i can see the data in count-views.yaml, however i don't know how to display it on my blog pages as well as other individual pages.
I am not a coder or developer.

I am using gantry5 with helium theme.

Could you please how to do this?
Thanks a lot.

**Comment by Perlkonig** [comment]
I don't use Gantry. As per the docs, the count data is dumped into the Twig variable `viewcounts`. You can access it like any other variable. I'm afraid you'll have to go to the main forums with help on how to access that via Gantry. Sorry!
