### ISSUE TITLE
hypen ' - ' does not recognize with the {% if} statement

### ISSUE THREAD

**Issue by duceduc** [Perlkonig/grav-plugin-count-views#7]
This file naming convention 'count-views.ymal' isn't recognized by

{% if config.plugins.count-views.enabled %}
........
{% endif %}

'count_views.yaml' will work.

**Comment by Perlkonig** [comment]
This is known. This is why I none of my other plugins use hyphens in the name. The correct way to call such a plugin is as follows: `{% if config.plugins['count-views'].enabled%}`. I apologize for the inconvenience, but renaming it is not really feasible at this point. Cheers!

**Comment by Perlkonig** [comment]
But I'll add this to the README. I didn't realize I hadn't yet.
