### ISSUE TITLE
Count-views not compatible with 'Hide home route in URLs'

### ISSUE THREAD

**Issue by awrog** [Perlkonig/grav-plugin-count-views#8]
When I activate 'Hide home route in URLs', pages are no longer recognized.

![screenshot - 5_17_2018 2_15_35 pm](https://user-images.githubusercontent.com/12153667/40176781-d5da062e-59dc-11e8-963f-9bb24eadd1df.png)

Example from count-views.yaml

/home/verwijderen-niet-lid: 30 <- is displayed in widget

/verwerken-boekstukken: 22 <- is not displayed in widget

**Comment by Perlkonig** [comment]
The plugin doesn't come with a widget. How did you code it? If the counts are being recorded, that's all the plugin can do for you.

**Comment by awrog** [comment]
Knowledge Base Theme -> Popular Articles

**Comment by Perlkonig** [comment]
If you look at the docs for that theme, there's talk of `articleroot`. Make sure that's set properly. If you're still having issues, I'm happy to help. But open a new issue over there. Thanks!

**Comment by awrog** [comment]
That solved it! Thanks.
